// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package querier

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/risingwavelabs/anclax/pkg/zgen/apigen"
)

const claimNormalTaskByGroup = `-- name: ClaimNormalTaskByGroup :one
WITH
    eligible AS (
        SELECT t.id, t.attributes, t.spec, t.status, t.unique_tag, t.started_at, t.created_at, t.updated_at, t.attempts, t.locked_at, t.worker_id, t.serial_key, t.serial_id, t.priority, t.weight, t.parent_task_id
        FROM anclax.tasks t
        WHERE
            t.status = 'pending'
            AND t.priority = 0
            AND (t.started_at IS NULL OR t.started_at < NOW())
            AND (t.locked_at IS NULL OR t.locked_at < $2)
            AND (
                $3::bool = false
                OR t.attributes->'labels' IS NULL
                OR jsonb_array_length(t.attributes->'labels') = 0
                OR (t.attributes->'labels' ?| $4::text[])
            )
            AND (
                (
                    $5::text = '__default__'
                    AND (
                        COALESCE(array_length($6::text[], 1), 0) = 0
                        OR
                        t.attributes->'labels' IS NULL
                        OR jsonb_array_length(t.attributes->'labels') = 0
                        OR NOT (t.attributes->'labels' ?| $6::text[])
                    )
                )
                OR (
                    $5::text <> '__default__'
                    AND (t.attributes->'labels' ? $5::text)
                )
            )
    ),
    locked_serial_keys AS (
        SELECT DISTINCT t.serial_key
        FROM anclax.tasks t
        WHERE
            t.serial_key IS NOT NULL
            AND t.locked_at IS NOT NULL
            AND t.locked_at >= $2
    ),
    candidate AS (
        SELECT e.id
        FROM eligible e
        WHERE
            e.serial_key IS NULL
            OR (
                NOT EXISTS (
                    SELECT 1 FROM locked_serial_keys l WHERE l.serial_key = e.serial_key
                )
                AND NOT EXISTS (
                    SELECT 1
                    FROM anclax.tasks s
                    WHERE
                        s.serial_key = e.serial_key
                        AND s.status = 'pending'
                        AND ROW(
                            s.serial_id IS NULL,
                            COALESCE(s.serial_id, 2147483647),
                            s.created_at,
                            COALESCE(s.started_at, '-infinity'::timestamptz),
                            s.id
                        ) < ROW(
                            e.serial_id IS NULL,
                            COALESCE(e.serial_id, 2147483647),
                            e.created_at,
                            COALESCE(e.started_at, '-infinity'::timestamptz),
                            e.id
                        )
                )
            )
        ORDER BY e.weight DESC, e.created_at, e.id
        LIMIT 1
    )
UPDATE anclax.tasks
SET
    locked_at = CURRENT_TIMESTAMP,
    worker_id = $1,
    attempts = attempts + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    anclax.tasks.id = (SELECT id FROM candidate)
    AND anclax.tasks.status = 'pending'
    AND (anclax.tasks.locked_at IS NULL OR anclax.tasks.locked_at < $2)
RETURNING id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id, priority, weight, parent_task_id
`

type ClaimNormalTaskByGroupParams struct {
	WorkerID       uuid.NullUUID
	LockExpiry     *time.Time
	HasLabels      bool
	Labels         []string
	GroupName      string
	WeightedLabels []string
}

func (q *Queries) ClaimNormalTaskByGroup(ctx context.Context, arg ClaimNormalTaskByGroupParams) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, claimNormalTaskByGroup,
		arg.WorkerID,
		arg.LockExpiry,
		arg.HasLabels,
		arg.Labels,
		arg.GroupName,
		arg.WeightedLabels,
	)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
		&i.Priority,
		&i.Weight,
		&i.ParentTaskID,
	)
	return &i, err
}

const claimStrictTask = `-- name: ClaimStrictTask :one
WITH
    eligible AS (
        SELECT t.id, t.attributes, t.spec, t.status, t.unique_tag, t.started_at, t.created_at, t.updated_at, t.attempts, t.locked_at, t.worker_id, t.serial_key, t.serial_id, t.priority, t.weight, t.parent_task_id
        FROM anclax.tasks t
        WHERE
            t.status = 'pending'
            AND t.priority > 0
            AND (t.started_at IS NULL OR t.started_at < NOW())
            AND (t.locked_at IS NULL OR t.locked_at < $2)
            AND (
                $3::bool = false
                OR t.attributes->'labels' IS NULL
                OR jsonb_array_length(t.attributes->'labels') = 0
                OR (t.attributes->'labels' ?| $4::text[])
            )
    ),
    locked_serial_keys AS (
        SELECT DISTINCT t.serial_key
        FROM anclax.tasks t
        WHERE
            t.serial_key IS NOT NULL
            AND t.locked_at IS NOT NULL
            AND t.locked_at >= $2
    ),
    candidate AS (
        SELECT e.id
        FROM eligible e
        WHERE
            e.serial_key IS NULL
            OR (
                NOT EXISTS (
                    SELECT 1 FROM locked_serial_keys l WHERE l.serial_key = e.serial_key
                )
                AND NOT EXISTS (
                    SELECT 1
                    FROM anclax.tasks s
                    WHERE
                        s.serial_key = e.serial_key
                        AND s.status = 'pending'
                        AND ROW(
                            s.serial_id IS NULL,
                            COALESCE(s.serial_id, 2147483647),
                            s.created_at,
                            COALESCE(s.started_at, '-infinity'::timestamptz),
                            s.id
                        ) < ROW(
                            e.serial_id IS NULL,
                            COALESCE(e.serial_id, 2147483647),
                            e.created_at,
                            COALESCE(e.started_at, '-infinity'::timestamptz),
                            e.id
                        )
                )
            )
        ORDER BY e.priority DESC, e.created_at, e.id
        LIMIT 1
    )
UPDATE anclax.tasks
SET
    locked_at = CURRENT_TIMESTAMP,
    worker_id = $1,
    attempts = attempts + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    anclax.tasks.id = (SELECT id FROM candidate)
    AND anclax.tasks.status = 'pending'
    AND (anclax.tasks.locked_at IS NULL OR anclax.tasks.locked_at < $2)
RETURNING id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id, priority, weight, parent_task_id
`

type ClaimStrictTaskParams struct {
	WorkerID   uuid.NullUUID
	LockExpiry *time.Time
	HasLabels  bool
	Labels     []string
}

func (q *Queries) ClaimStrictTask(ctx context.Context, arg ClaimStrictTaskParams) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, claimStrictTask,
		arg.WorkerID,
		arg.LockExpiry,
		arg.HasLabels,
		arg.Labels,
	)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
		&i.Priority,
		&i.Weight,
		&i.ParentTaskID,
	)
	return &i, err
}

const claimTask = `-- name: ClaimTask :one
WITH
    eligible AS (
        SELECT t.id, t.attributes, t.spec, t.status, t.unique_tag, t.started_at, t.created_at, t.updated_at, t.attempts, t.locked_at, t.worker_id, t.serial_key, t.serial_id, t.priority, t.weight, t.parent_task_id
        FROM anclax.tasks t
        WHERE
            t.status = 'pending'
            AND (t.started_at IS NULL OR t.started_at < NOW())
            AND (t.locked_at IS NULL OR t.locked_at < $2)
            AND (
                $3::bool = false
                OR t.attributes->'labels' IS NULL
                OR jsonb_array_length(t.attributes->'labels') = 0
                OR (t.attributes->'labels' ?| $4::text[])
            )
    ),
    locked_serial_keys AS (
        SELECT DISTINCT t.serial_key
        FROM anclax.tasks t
        WHERE
            t.serial_key IS NOT NULL
            AND t.locked_at IS NOT NULL
            AND t.locked_at >= $2
    ),
    candidate AS (
        SELECT e.id
        FROM eligible e
        WHERE
            e.serial_key IS NULL
            OR (
                NOT EXISTS (
                    SELECT 1 FROM locked_serial_keys l WHERE l.serial_key = e.serial_key
                )
                AND NOT EXISTS (
                    SELECT 1
                    FROM anclax.tasks s
                    WHERE
                        s.serial_key = e.serial_key
                        AND s.status = 'pending'
                        AND ROW(
                            s.serial_id IS NULL,
                            COALESCE(s.serial_id, 2147483647),
                            s.created_at,
                            COALESCE(s.started_at, '-infinity'::timestamptz),
                            s.id
                        ) < ROW(
                            e.serial_id IS NULL,
                            COALESCE(e.serial_id, 2147483647),
                            e.created_at,
                            COALESCE(e.started_at, '-infinity'::timestamptz),
                            e.id
                        )
                )
            )
        ORDER BY e.priority DESC, e.created_at, e.id
        LIMIT 1
    )
UPDATE anclax.tasks
SET
    locked_at = CURRENT_TIMESTAMP,
    worker_id = $1,
    attempts = attempts + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    anclax.tasks.id = (SELECT id FROM candidate)
    AND anclax.tasks.status = 'pending'
    AND (anclax.tasks.locked_at IS NULL OR anclax.tasks.locked_at < $2)
RETURNING id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id, priority, weight, parent_task_id
`

type ClaimTaskParams struct {
	WorkerID   uuid.NullUUID
	LockExpiry *time.Time
	HasLabels  bool
	Labels     []string
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, claimTask,
		arg.WorkerID,
		arg.LockExpiry,
		arg.HasLabels,
		arg.Labels,
	)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
		&i.Priority,
		&i.Weight,
		&i.ParentTaskID,
	)
	return &i, err
}

const claimTaskByID = `-- name: ClaimTaskByID :one
WITH
    eligible AS (
        SELECT t.id, t.attributes, t.spec, t.status, t.unique_tag, t.started_at, t.created_at, t.updated_at, t.attempts, t.locked_at, t.worker_id, t.serial_key, t.serial_id, t.priority, t.weight, t.parent_task_id
        FROM anclax.tasks t
        WHERE
            t.id = $3
            AND t.status = 'pending'
            AND (t.started_at IS NULL OR t.started_at < NOW())
            AND (t.locked_at IS NULL OR t.locked_at < $2)
            AND (
                $4::bool = false
                OR t.attributes->'labels' IS NULL
                OR jsonb_array_length(t.attributes->'labels') = 0
                OR (t.attributes->'labels' ?| $5::text[])
            )
    ),
    locked_serial_keys AS (
        SELECT DISTINCT t.serial_key
        FROM anclax.tasks t
        WHERE
            t.serial_key IS NOT NULL
            AND t.locked_at IS NOT NULL
            AND t.locked_at >= $2
    ),
    candidate AS (
        SELECT e.id
        FROM eligible e
        WHERE
            e.serial_key IS NULL
            OR (
                NOT EXISTS (
                    SELECT 1 FROM locked_serial_keys l WHERE l.serial_key = e.serial_key
                )
                AND NOT EXISTS (
                    SELECT 1
                    FROM anclax.tasks s
                    WHERE
                        s.serial_key = e.serial_key
                        AND s.status = 'pending'
                        AND ROW(
                            s.serial_id IS NULL,
                            COALESCE(s.serial_id, 2147483647),
                            s.created_at,
                            COALESCE(s.started_at, '-infinity'::timestamptz),
                            s.id
                        ) < ROW(
                            e.serial_id IS NULL,
                            COALESCE(e.serial_id, 2147483647),
                            e.created_at,
                            COALESCE(e.started_at, '-infinity'::timestamptz),
                            e.id
                        )
                )
            )
        LIMIT 1
    )
UPDATE anclax.tasks
SET
    locked_at = CURRENT_TIMESTAMP,
    worker_id = $1,
    attempts = attempts + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    anclax.tasks.id = (SELECT id FROM candidate)
    AND anclax.tasks.status = 'pending'
    AND (anclax.tasks.locked_at IS NULL OR anclax.tasks.locked_at < $2)
RETURNING id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id, priority, weight, parent_task_id
`

type ClaimTaskByIDParams struct {
	WorkerID   uuid.NullUUID
	LockExpiry *time.Time
	ID         int32
	HasLabels  bool
	Labels     []string
}

func (q *Queries) ClaimTaskByID(ctx context.Context, arg ClaimTaskByIDParams) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, claimTaskByID,
		arg.WorkerID,
		arg.LockExpiry,
		arg.ID,
		arg.HasLabels,
		arg.Labels,
	)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
		&i.Priority,
		&i.Weight,
		&i.ParentTaskID,
	)
	return &i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO anclax.tasks (attributes, spec, status, started_at, unique_tag, parent_task_id, serial_key, serial_id, priority, weight)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) ON CONFLICT (unique_tag) DO NOTHING RETURNING id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id, priority, weight, parent_task_id
`

type CreateTaskParams struct {
	Attributes   apigen.TaskAttributes
	Spec         apigen.TaskSpec
	Status       string
	StartedAt    *time.Time
	UniqueTag    *string
	ParentTaskID *int32
	SerialKey    *string
	SerialID     *int32
	Priority     int32
	Weight       int32
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Attributes,
		arg.Spec,
		arg.Status,
		arg.StartedAt,
		arg.UniqueTag,
		arg.ParentTaskID,
		arg.SerialKey,
		arg.SerialID,
		arg.Priority,
		arg.Weight,
	)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
		&i.Priority,
		&i.Weight,
		&i.ParentTaskID,
	)
	return &i, err
}

const getLastTaskErrorEvent = `-- name: GetLastTaskErrorEvent :one
SELECT id, spec, created_at FROM anclax.events
WHERE spec->>'type' = 'TaskError'
  AND (spec->'taskError'->>'taskID')::int = $1::int
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastTaskErrorEvent(ctx context.Context, taskID int32) (*AnclaxEvent, error) {
	row := q.db.QueryRow(ctx, getLastTaskErrorEvent, taskID)
	var i AnclaxEvent
	err := row.Scan(&i.ID, &i.Spec, &i.CreatedAt)
	return &i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id, priority, weight, parent_task_id FROM anclax.tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id int32) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
		&i.Priority,
		&i.Weight,
		&i.ParentTaskID,
	)
	return &i, err
}

const getTaskByUniqueTag = `-- name: GetTaskByUniqueTag :one
SELECT id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id, priority, weight, parent_task_id FROM anclax.tasks
WHERE unique_tag = $1
`

func (q *Queries) GetTaskByUniqueTag(ctx context.Context, uniqueTag *string) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, getTaskByUniqueTag, uniqueTag)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
		&i.Priority,
		&i.Weight,
		&i.ParentTaskID,
	)
	return &i, err
}

const incrementAttempts = `-- name: IncrementAttempts :exec
UPDATE anclax.tasks
SET attempts = attempts + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) IncrementAttempts(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementAttempts, id)
	return err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO anclax.events (spec)
VALUES ($1)
RETURNING id, spec, created_at
`

func (q *Queries) InsertEvent(ctx context.Context, spec apigen.EventSpec) (*AnclaxEvent, error) {
	row := q.db.QueryRow(ctx, insertEvent, spec)
	var i AnclaxEvent
	err := row.Scan(&i.ID, &i.Spec, &i.CreatedAt)
	return &i, err
}

const listAllPendingTasks = `-- name: ListAllPendingTasks :many
SELECT id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id, priority, weight, parent_task_id FROM anclax.tasks
WHERE
    status = 'pending'
    AND (
        started_at IS NULL OR started_at < NOW()
    )
`

func (q *Queries) ListAllPendingTasks(ctx context.Context) ([]*AnclaxTask, error) {
	rows, err := q.db.Query(ctx, listAllPendingTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AnclaxTask
	for rows.Next() {
		var i AnclaxTask
		if err := rows.Scan(
			&i.ID,
			&i.Attributes,
			&i.Spec,
			&i.Status,
			&i.UniqueTag,
			&i.StartedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Attempts,
			&i.LockedAt,
			&i.WorkerID,
			&i.SerialKey,
			&i.SerialID,
			&i.Priority,
			&i.Weight,
			&i.ParentTaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDescendantIDs = `-- name: ListTaskDescendantIDs :many
WITH RECURSIVE descendants AS (
    SELECT t.id
    FROM anclax.tasks t
    WHERE t.parent_task_id = $1
    UNION ALL
    SELECT t.id
    FROM anclax.tasks t
    JOIN descendants d ON t.parent_task_id = d.id
)
SELECT id FROM descendants
`

func (q *Queries) ListTaskDescendantIDs(ctx context.Context, parentTaskID *int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, listTaskDescendantIDs, parentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTaskLock = `-- name: RefreshTaskLock :one
UPDATE anclax.tasks
SET locked_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND worker_id = $2
RETURNING id
`

type RefreshTaskLockParams struct {
	ID       int32
	WorkerID uuid.NullUUID
}

func (q *Queries) RefreshTaskLock(ctx context.Context, arg RefreshTaskLockParams) (int32, error) {
	row := q.db.QueryRow(ctx, refreshTaskLock, arg.ID, arg.WorkerID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const releaseTaskLockByWorker = `-- name: ReleaseTaskLockByWorker :one
UPDATE anclax.tasks
SET locked_at = NULL, worker_id = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND worker_id = $2
RETURNING id
`

type ReleaseTaskLockByWorkerParams struct {
	ID       int32
	WorkerID uuid.NullUUID
}

func (q *Queries) ReleaseTaskLockByWorker(ctx context.Context, arg ReleaseTaskLockByWorkerParams) (int32, error) {
	row := q.db.QueryRow(ctx, releaseTaskLockByWorker, arg.ID, arg.WorkerID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updatePendingTaskPriorityByLabels = `-- name: UpdatePendingTaskPriorityByLabels :execrows
UPDATE anclax.tasks
SET
    priority = GREATEST($1::int, 0),
    attributes = jsonb_set(attributes, '{priority}', to_jsonb(GREATEST($1::int, 0)), true),
    updated_at = CURRENT_TIMESTAMP
WHERE
    status = 'pending'
    AND (
        ($2::bool = true AND attributes->'labels' ?| $3::text[])
        OR (
            $2::bool = false
            AND (
                attributes->'labels' IS NULL
                OR jsonb_array_length(attributes->'labels') = 0
            )
        )
    )
`

type UpdatePendingTaskPriorityByLabelsParams struct {
	Priority  int32
	HasLabels bool
	Labels    []string
}

func (q *Queries) UpdatePendingTaskPriorityByLabels(ctx context.Context, arg UpdatePendingTaskPriorityByLabelsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePendingTaskPriorityByLabels, arg.Priority, arg.HasLabels, arg.Labels)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePendingTaskWeightByLabels = `-- name: UpdatePendingTaskWeightByLabels :execrows
UPDATE anclax.tasks
SET
    weight = GREATEST($1::int, 1),
    attributes = jsonb_set(attributes, '{weight}', to_jsonb(GREATEST($1::int, 1)), true),
    updated_at = CURRENT_TIMESTAMP
WHERE
    status = 'pending'
    AND (
        ($2::bool = true AND attributes->'labels' ?| $3::text[])
        OR (
            $2::bool = false
            AND (
                attributes->'labels' IS NULL
                OR jsonb_array_length(attributes->'labels') = 0
            )
        )
    )
`

type UpdatePendingTaskWeightByLabelsParams struct {
	Weight    int32
	HasLabels bool
	Labels    []string
}

func (q *Queries) UpdatePendingTaskWeightByLabels(ctx context.Context, arg UpdatePendingTaskWeightByLabelsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePendingTaskWeightByLabels, arg.Weight, arg.HasLabels, arg.Labels)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE anclax.tasks
SET
    attributes = $2,
    spec = $3,
    started_at = $4,
    serial_key = $5,
    serial_id = $6,
    priority = $7,
    weight = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTaskParams struct {
	ID         int32
	Attributes apigen.TaskAttributes
	Spec       apigen.TaskSpec
	StartedAt  *time.Time
	SerialKey  *string
	SerialID   *int32
	Priority   int32
	Weight     int32
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.ID,
		arg.Attributes,
		arg.Spec,
		arg.StartedAt,
		arg.SerialKey,
		arg.SerialID,
		arg.Priority,
		arg.Weight,
	)
	return err
}

const updateTaskStartedAt = `-- name: UpdateTaskStartedAt :exec
UPDATE anclax.tasks
SET started_at = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTaskStartedAtParams struct {
	ID        int32
	StartedAt *time.Time
}

func (q *Queries) UpdateTaskStartedAt(ctx context.Context, arg UpdateTaskStartedAtParams) error {
	_, err := q.db.Exec(ctx, updateTaskStartedAt, arg.ID, arg.StartedAt)
	return err
}

const updateTaskStartedAtByWorker = `-- name: UpdateTaskStartedAtByWorker :one
UPDATE anclax.tasks
SET started_at = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND worker_id = $3
RETURNING id
`

type UpdateTaskStartedAtByWorkerParams struct {
	ID        int32
	StartedAt *time.Time
	WorkerID  uuid.NullUUID
}

func (q *Queries) UpdateTaskStartedAtByWorker(ctx context.Context, arg UpdateTaskStartedAtByWorkerParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateTaskStartedAtByWorker, arg.ID, arg.StartedAt, arg.WorkerID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE anclax.tasks
SET
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     int32
	Status string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}

const updateTaskStatusByWorker = `-- name: UpdateTaskStatusByWorker :one
UPDATE anclax.tasks
SET
    status = $2,
    locked_at = NULL,
    worker_id = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND worker_id = $3
RETURNING id
`

type UpdateTaskStatusByWorkerParams struct {
	ID       int32
	Status   string
	WorkerID uuid.NullUUID
}

func (q *Queries) UpdateTaskStatusByWorker(ctx context.Context, arg UpdateTaskStatusByWorkerParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateTaskStatusByWorker, arg.ID, arg.Status, arg.WorkerID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const verifyTaskOwnership = `-- name: VerifyTaskOwnership :one
SELECT id FROM anclax.tasks
WHERE id = $1 AND worker_id = $2
`

type VerifyTaskOwnershipParams struct {
	ID       int32
	WorkerID uuid.NullUUID
}

func (q *Queries) VerifyTaskOwnership(ctx context.Context, arg VerifyTaskOwnershipParams) (int32, error) {
	row := q.db.QueryRow(ctx, verifyTaskOwnership, arg.ID, arg.WorkerID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
