// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/zcore/model/model.go
//
// Generated by this command:
//
//	mockgen -source pkg/zcore/model/model.go -destination pkg/zcore/model/mock_gen.go -package model
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	json "encoding/json"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	core "github.com/risingwavelabs/anclax/core"
	apigen "github.com/risingwavelabs/anclax/pkg/zgen/apigen"
	querier "github.com/risingwavelabs/anclax/pkg/zgen/querier"
	gomock "go.uber.org/mock/gomock"
)

// MockModelInterface is a mock of ModelInterface interface.
type MockModelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockModelInterfaceMockRecorder
	isgomock struct{}
}

// MockModelInterfaceMockRecorder is the mock recorder for MockModelInterface.
type MockModelInterfaceMockRecorder struct {
	mock *MockModelInterface
}

// NewMockModelInterface creates a new mock instance.
func NewMockModelInterface(ctrl *gomock.Controller) *MockModelInterface {
	mock := &MockModelInterface{ctrl: ctrl}
	mock.recorder = &MockModelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelInterface) EXPECT() *MockModelInterfaceMockRecorder {
	return m.recorder
}

// ClaimNormalTaskByGroup mocks base method.
func (m *MockModelInterface) ClaimNormalTaskByGroup(ctx context.Context, arg querier.ClaimNormalTaskByGroupParams) (*querier.AnclaxTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNormalTaskByGroup", ctx, arg)
	ret0, _ := ret[0].(*querier.AnclaxTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNormalTaskByGroup indicates an expected call of ClaimNormalTaskByGroup.
func (mr *MockModelInterfaceMockRecorder) ClaimNormalTaskByGroup(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNormalTaskByGroup", reflect.TypeOf((*MockModelInterface)(nil).ClaimNormalTaskByGroup), ctx, arg)
}

// ClaimStrictTask mocks base method.
func (m *MockModelInterface) ClaimStrictTask(ctx context.Context, arg querier.ClaimStrictTaskParams) (*querier.AnclaxTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimStrictTask", ctx, arg)
	ret0, _ := ret[0].(*querier.AnclaxTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimStrictTask indicates an expected call of ClaimStrictTask.
func (mr *MockModelInterfaceMockRecorder) ClaimStrictTask(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimStrictTask", reflect.TypeOf((*MockModelInterface)(nil).ClaimStrictTask), ctx, arg)
}

// ClaimTask mocks base method.
func (m *MockModelInterface) ClaimTask(ctx context.Context, arg querier.ClaimTaskParams) (*querier.AnclaxTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimTask", ctx, arg)
	ret0, _ := ret[0].(*querier.AnclaxTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimTask indicates an expected call of ClaimTask.
func (mr *MockModelInterfaceMockRecorder) ClaimTask(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimTask", reflect.TypeOf((*MockModelInterface)(nil).ClaimTask), ctx, arg)
}

// ClaimTaskByID mocks base method.
func (m *MockModelInterface) ClaimTaskByID(ctx context.Context, arg querier.ClaimTaskByIDParams) (*querier.AnclaxTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimTaskByID", ctx, arg)
	ret0, _ := ret[0].(*querier.AnclaxTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimTaskByID indicates an expected call of ClaimTaskByID.
func (mr *MockModelInterfaceMockRecorder) ClaimTaskByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimTaskByID", reflect.TypeOf((*MockModelInterface)(nil).ClaimTaskByID), ctx, arg)
}

// Close mocks base method.
func (m *MockModelInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockModelInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockModelInterface)(nil).Close))
}

// CreateKeyPair mocks base method.
func (m *MockModelInterface) CreateKeyPair(ctx context.Context, arg querier.CreateKeyPairParams) (*querier.AnclaxAccessKeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeyPair", ctx, arg)
	ret0, _ := ret[0].(*querier.AnclaxAccessKeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKeyPair indicates an expected call of CreateKeyPair.
func (mr *MockModelInterfaceMockRecorder) CreateKeyPair(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyPair", reflect.TypeOf((*MockModelInterface)(nil).CreateKeyPair), ctx, arg)
}

// CreateOpaqueKey mocks base method.
func (m *MockModelInterface) CreateOpaqueKey(ctx context.Context, arg querier.CreateOpaqueKeyParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpaqueKey", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOpaqueKey indicates an expected call of CreateOpaqueKey.
func (mr *MockModelInterfaceMockRecorder) CreateOpaqueKey(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpaqueKey", reflect.TypeOf((*MockModelInterface)(nil).CreateOpaqueKey), ctx, arg)
}

// CreateOrg mocks base method.
func (m *MockModelInterface) CreateOrg(ctx context.Context, name string) (*querier.AnclaxOrg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrg", ctx, name)
	ret0, _ := ret[0].(*querier.AnclaxOrg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrg indicates an expected call of CreateOrg.
func (mr *MockModelInterfaceMockRecorder) CreateOrg(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrg", reflect.TypeOf((*MockModelInterface)(nil).CreateOrg), ctx, name)
}

// CreateTask mocks base method.
func (m *MockModelInterface) CreateTask(ctx context.Context, arg querier.CreateTaskParams) (*querier.AnclaxTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, arg)
	ret0, _ := ret[0].(*querier.AnclaxTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockModelInterfaceMockRecorder) CreateTask(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockModelInterface)(nil).CreateTask), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockModelInterface) CreateUser(ctx context.Context, arg querier.CreateUserParams) (*querier.AnclaxUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(*querier.AnclaxUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockModelInterfaceMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockModelInterface)(nil).CreateUser), ctx, arg)
}

// CreateWorkerRuntimeConfig mocks base method.
func (m *MockModelInterface) CreateWorkerRuntimeConfig(ctx context.Context, payload json.RawMessage) (*querier.AnclaxWorkerRuntimeConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkerRuntimeConfig", ctx, payload)
	ret0, _ := ret[0].(*querier.AnclaxWorkerRuntimeConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkerRuntimeConfig indicates an expected call of CreateWorkerRuntimeConfig.
func (mr *MockModelInterfaceMockRecorder) CreateWorkerRuntimeConfig(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkerRuntimeConfig", reflect.TypeOf((*MockModelInterface)(nil).CreateWorkerRuntimeConfig), ctx, payload)
}

// DeleteKeyPair mocks base method.
func (m *MockModelInterface) DeleteKeyPair(ctx context.Context, accessKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeyPair", ctx, accessKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKeyPair indicates an expected call of DeleteKeyPair.
func (mr *MockModelInterfaceMockRecorder) DeleteKeyPair(ctx, accessKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeyPair", reflect.TypeOf((*MockModelInterface)(nil).DeleteKeyPair), ctx, accessKey)
}

// DeleteOpaqueKey mocks base method.
func (m *MockModelInterface) DeleteOpaqueKey(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOpaqueKey", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOpaqueKey indicates an expected call of DeleteOpaqueKey.
func (mr *MockModelInterfaceMockRecorder) DeleteOpaqueKey(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOpaqueKey", reflect.TypeOf((*MockModelInterface)(nil).DeleteOpaqueKey), ctx, id)
}

// DeleteOpaqueKeys mocks base method.
func (m *MockModelInterface) DeleteOpaqueKeys(ctx context.Context, userID *int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOpaqueKeys", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOpaqueKeys indicates an expected call of DeleteOpaqueKeys.
func (mr *MockModelInterfaceMockRecorder) DeleteOpaqueKeys(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOpaqueKeys", reflect.TypeOf((*MockModelInterface)(nil).DeleteOpaqueKeys), ctx, userID)
}

// DeleteUserByName mocks base method.
func (m *MockModelInterface) DeleteUserByName(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserByName", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserByName indicates an expected call of DeleteUserByName.
func (mr *MockModelInterfaceMockRecorder) DeleteUserByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserByName", reflect.TypeOf((*MockModelInterface)(nil).DeleteUserByName), ctx, name)
}

// GetKeyPair mocks base method.
func (m *MockModelInterface) GetKeyPair(ctx context.Context, accessKey string) (*querier.AnclaxAccessKeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyPair", ctx, accessKey)
	ret0, _ := ret[0].(*querier.AnclaxAccessKeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyPair indicates an expected call of GetKeyPair.
func (mr *MockModelInterfaceMockRecorder) GetKeyPair(ctx, accessKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyPair", reflect.TypeOf((*MockModelInterface)(nil).GetKeyPair), ctx, accessKey)
}

// GetLastTaskErrorEvent mocks base method.
func (m *MockModelInterface) GetLastTaskErrorEvent(ctx context.Context, taskID int32) (*querier.AnclaxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastTaskErrorEvent", ctx, taskID)
	ret0, _ := ret[0].(*querier.AnclaxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastTaskErrorEvent indicates an expected call of GetLastTaskErrorEvent.
func (mr *MockModelInterfaceMockRecorder) GetLastTaskErrorEvent(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastTaskErrorEvent", reflect.TypeOf((*MockModelInterface)(nil).GetLastTaskErrorEvent), ctx, taskID)
}

// GetLatestWorkerRuntimeConfig mocks base method.
func (m *MockModelInterface) GetLatestWorkerRuntimeConfig(ctx context.Context) (*querier.AnclaxWorkerRuntimeConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestWorkerRuntimeConfig", ctx)
	ret0, _ := ret[0].(*querier.AnclaxWorkerRuntimeConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestWorkerRuntimeConfig indicates an expected call of GetLatestWorkerRuntimeConfig.
func (mr *MockModelInterfaceMockRecorder) GetLatestWorkerRuntimeConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestWorkerRuntimeConfig", reflect.TypeOf((*MockModelInterface)(nil).GetLatestWorkerRuntimeConfig), ctx)
}

// GetOpaqueKey mocks base method.
func (m *MockModelInterface) GetOpaqueKey(ctx context.Context, id int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpaqueKey", ctx, id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpaqueKey indicates an expected call of GetOpaqueKey.
func (mr *MockModelInterfaceMockRecorder) GetOpaqueKey(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpaqueKey", reflect.TypeOf((*MockModelInterface)(nil).GetOpaqueKey), ctx, id)
}

// GetOrg mocks base method.
func (m *MockModelInterface) GetOrg(ctx context.Context, id int32) (*querier.AnclaxOrg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrg", ctx, id)
	ret0, _ := ret[0].(*querier.AnclaxOrg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrg indicates an expected call of GetOrg.
func (mr *MockModelInterfaceMockRecorder) GetOrg(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrg", reflect.TypeOf((*MockModelInterface)(nil).GetOrg), ctx, id)
}

// GetOrgByName mocks base method.
func (m *MockModelInterface) GetOrgByName(ctx context.Context, name string) (*querier.AnclaxOrg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgByName", ctx, name)
	ret0, _ := ret[0].(*querier.AnclaxOrg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrgByName indicates an expected call of GetOrgByName.
func (mr *MockModelInterfaceMockRecorder) GetOrgByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgByName", reflect.TypeOf((*MockModelInterface)(nil).GetOrgByName), ctx, name)
}

// GetTaskByID mocks base method.
func (m *MockModelInterface) GetTaskByID(ctx context.Context, id int32) (*querier.AnclaxTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, id)
	ret0, _ := ret[0].(*querier.AnclaxTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockModelInterfaceMockRecorder) GetTaskByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockModelInterface)(nil).GetTaskByID), ctx, id)
}

// GetTaskByUniqueTag mocks base method.
func (m *MockModelInterface) GetTaskByUniqueTag(ctx context.Context, uniqueTag *string) (*querier.AnclaxTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByUniqueTag", ctx, uniqueTag)
	ret0, _ := ret[0].(*querier.AnclaxTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByUniqueTag indicates an expected call of GetTaskByUniqueTag.
func (mr *MockModelInterfaceMockRecorder) GetTaskByUniqueTag(ctx, uniqueTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByUniqueTag", reflect.TypeOf((*MockModelInterface)(nil).GetTaskByUniqueTag), ctx, uniqueTag)
}

// GetUser mocks base method.
func (m *MockModelInterface) GetUser(ctx context.Context, id int32) (*querier.AnclaxUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(*querier.AnclaxUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockModelInterfaceMockRecorder) GetUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockModelInterface)(nil).GetUser), ctx, id)
}

// GetUserByName mocks base method.
func (m *MockModelInterface) GetUserByName(ctx context.Context, name string) (*querier.AnclaxUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByName", ctx, name)
	ret0, _ := ret[0].(*querier.AnclaxUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByName indicates an expected call of GetUserByName.
func (mr *MockModelInterfaceMockRecorder) GetUserByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByName", reflect.TypeOf((*MockModelInterface)(nil).GetUserByName), ctx, name)
}

// GetUserDefaultOrg mocks base method.
func (m *MockModelInterface) GetUserDefaultOrg(ctx context.Context, userID int32) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDefaultOrg", ctx, userID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDefaultOrg indicates an expected call of GetUserDefaultOrg.
func (mr *MockModelInterfaceMockRecorder) GetUserDefaultOrg(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDefaultOrg", reflect.TypeOf((*MockModelInterface)(nil).GetUserDefaultOrg), ctx, userID)
}

// GetWorkerRuntimeConfigByVersion mocks base method.
func (m *MockModelInterface) GetWorkerRuntimeConfigByVersion(ctx context.Context, version int64) (*querier.AnclaxWorkerRuntimeConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerRuntimeConfigByVersion", ctx, version)
	ret0, _ := ret[0].(*querier.AnclaxWorkerRuntimeConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkerRuntimeConfigByVersion indicates an expected call of GetWorkerRuntimeConfigByVersion.
func (mr *MockModelInterfaceMockRecorder) GetWorkerRuntimeConfigByVersion(ctx, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerRuntimeConfigByVersion", reflect.TypeOf((*MockModelInterface)(nil).GetWorkerRuntimeConfigByVersion), ctx, version)
}

// InTransaction mocks base method.
func (m *MockModelInterface) InTransaction() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction")
	ret0, _ := ret[0].(bool)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MockModelInterfaceMockRecorder) InTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*MockModelInterface)(nil).InTransaction))
}

// IncrementAttempts mocks base method.
func (m *MockModelInterface) IncrementAttempts(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAttempts", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAttempts indicates an expected call of IncrementAttempts.
func (mr *MockModelInterfaceMockRecorder) IncrementAttempts(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAttempts", reflect.TypeOf((*MockModelInterface)(nil).IncrementAttempts), ctx, id)
}

// InsertEvent mocks base method.
func (m *MockModelInterface) InsertEvent(ctx context.Context, spec apigen.EventSpec) (*querier.AnclaxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvent", ctx, spec)
	ret0, _ := ret[0].(*querier.AnclaxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEvent indicates an expected call of InsertEvent.
func (mr *MockModelInterfaceMockRecorder) InsertEvent(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvent", reflect.TypeOf((*MockModelInterface)(nil).InsertEvent), ctx, spec)
}

// InsertOrgOwner mocks base method.
func (m *MockModelInterface) InsertOrgOwner(ctx context.Context, arg querier.InsertOrgOwnerParams) (*querier.AnclaxOrgOwner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrgOwner", ctx, arg)
	ret0, _ := ret[0].(*querier.AnclaxOrgOwner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOrgOwner indicates an expected call of InsertOrgOwner.
func (mr *MockModelInterfaceMockRecorder) InsertOrgOwner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrgOwner", reflect.TypeOf((*MockModelInterface)(nil).InsertOrgOwner), ctx, arg)
}

// InsertOrgUser mocks base method.
func (m *MockModelInterface) InsertOrgUser(ctx context.Context, arg querier.InsertOrgUserParams) (*querier.AnclaxOrgUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrgUser", ctx, arg)
	ret0, _ := ret[0].(*querier.AnclaxOrgUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOrgUser indicates an expected call of InsertOrgUser.
func (mr *MockModelInterfaceMockRecorder) InsertOrgUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrgUser", reflect.TypeOf((*MockModelInterface)(nil).InsertOrgUser), ctx, arg)
}

// IsUsernameExists mocks base method.
func (m *MockModelInterface) IsUsernameExists(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUsernameExists", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUsernameExists indicates an expected call of IsUsernameExists.
func (mr *MockModelInterfaceMockRecorder) IsUsernameExists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUsernameExists", reflect.TypeOf((*MockModelInterface)(nil).IsUsernameExists), ctx, name)
}

// ListAllPendingTasks mocks base method.
func (m *MockModelInterface) ListAllPendingTasks(ctx context.Context) ([]*querier.AnclaxTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPendingTasks", ctx)
	ret0, _ := ret[0].([]*querier.AnclaxTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllPendingTasks indicates an expected call of ListAllPendingTasks.
func (mr *MockModelInterfaceMockRecorder) ListAllPendingTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPendingTasks", reflect.TypeOf((*MockModelInterface)(nil).ListAllPendingTasks), ctx)
}

// ListLaggingAliveWorkers mocks base method.
func (m *MockModelInterface) ListLaggingAliveWorkers(ctx context.Context, arg querier.ListLaggingAliveWorkersParams) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLaggingAliveWorkers", ctx, arg)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLaggingAliveWorkers indicates an expected call of ListLaggingAliveWorkers.
func (mr *MockModelInterfaceMockRecorder) ListLaggingAliveWorkers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLaggingAliveWorkers", reflect.TypeOf((*MockModelInterface)(nil).ListLaggingAliveWorkers), ctx, arg)
}

// ListOnlineWorkerIDs mocks base method.
func (m *MockModelInterface) ListOnlineWorkerIDs(ctx context.Context, heartbeatCutoff time.Time) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOnlineWorkerIDs", ctx, heartbeatCutoff)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOnlineWorkerIDs indicates an expected call of ListOnlineWorkerIDs.
func (mr *MockModelInterfaceMockRecorder) ListOnlineWorkerIDs(ctx, heartbeatCutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOnlineWorkerIDs", reflect.TypeOf((*MockModelInterface)(nil).ListOnlineWorkerIDs), ctx, heartbeatCutoff)
}

// ListOrgs mocks base method.
func (m *MockModelInterface) ListOrgs(ctx context.Context, userID int32) ([]*querier.AnclaxOrg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgs", ctx, userID)
	ret0, _ := ret[0].([]*querier.AnclaxOrg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrgs indicates an expected call of ListOrgs.
func (mr *MockModelInterfaceMockRecorder) ListOrgs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgs", reflect.TypeOf((*MockModelInterface)(nil).ListOrgs), ctx, userID)
}

// ListTaskDescendantIDs mocks base method.
func (m *MockModelInterface) ListTaskDescendantIDs(ctx context.Context, parentTaskID *int32) ([]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskDescendantIDs", ctx, parentTaskID)
	ret0, _ := ret[0].([]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTaskDescendantIDs indicates an expected call of ListTaskDescendantIDs.
func (mr *MockModelInterfaceMockRecorder) ListTaskDescendantIDs(ctx, parentTaskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskDescendantIDs", reflect.TypeOf((*MockModelInterface)(nil).ListTaskDescendantIDs), ctx, parentTaskID)
}

// ListUsers mocks base method.
func (m *MockModelInterface) ListUsers(ctx context.Context) ([]*querier.ListUsersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]*querier.ListUsersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockModelInterfaceMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockModelInterface)(nil).ListUsers), ctx)
}

// MarkWorkerOffline mocks base method.
func (m *MockModelInterface) MarkWorkerOffline(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkWorkerOffline", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkWorkerOffline indicates an expected call of MarkWorkerOffline.
func (mr *MockModelInterfaceMockRecorder) MarkWorkerOffline(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkWorkerOffline", reflect.TypeOf((*MockModelInterface)(nil).MarkWorkerOffline), ctx, id)
}

// NotifyWorkerRuntimeConfig mocks base method.
func (m *MockModelInterface) NotifyWorkerRuntimeConfig(ctx context.Context, payload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyWorkerRuntimeConfig", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyWorkerRuntimeConfig indicates an expected call of NotifyWorkerRuntimeConfig.
func (mr *MockModelInterfaceMockRecorder) NotifyWorkerRuntimeConfig(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyWorkerRuntimeConfig", reflect.TypeOf((*MockModelInterface)(nil).NotifyWorkerRuntimeConfig), ctx, payload)
}

// NotifyWorkerRuntimeConfigAck mocks base method.
func (m *MockModelInterface) NotifyWorkerRuntimeConfigAck(ctx context.Context, payload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyWorkerRuntimeConfigAck", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyWorkerRuntimeConfigAck indicates an expected call of NotifyWorkerRuntimeConfigAck.
func (mr *MockModelInterfaceMockRecorder) NotifyWorkerRuntimeConfigAck(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyWorkerRuntimeConfigAck", reflect.TypeOf((*MockModelInterface)(nil).NotifyWorkerRuntimeConfigAck), ctx, payload)
}

// NotifyWorkerTaskInterrupt mocks base method.
func (m *MockModelInterface) NotifyWorkerTaskInterrupt(ctx context.Context, payload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyWorkerTaskInterrupt", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyWorkerTaskInterrupt indicates an expected call of NotifyWorkerTaskInterrupt.
func (mr *MockModelInterfaceMockRecorder) NotifyWorkerTaskInterrupt(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyWorkerTaskInterrupt", reflect.TypeOf((*MockModelInterface)(nil).NotifyWorkerTaskInterrupt), ctx, payload)
}

// NotifyWorkerTaskInterruptAck mocks base method.
func (m *MockModelInterface) NotifyWorkerTaskInterruptAck(ctx context.Context, payload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyWorkerTaskInterruptAck", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyWorkerTaskInterruptAck indicates an expected call of NotifyWorkerTaskInterruptAck.
func (mr *MockModelInterfaceMockRecorder) NotifyWorkerTaskInterruptAck(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyWorkerTaskInterruptAck", reflect.TypeOf((*MockModelInterface)(nil).NotifyWorkerTaskInterruptAck), ctx, payload)
}

// RefreshTaskLock mocks base method.
func (m *MockModelInterface) RefreshTaskLock(ctx context.Context, arg querier.RefreshTaskLockParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTaskLock", ctx, arg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTaskLock indicates an expected call of RefreshTaskLock.
func (mr *MockModelInterfaceMockRecorder) RefreshTaskLock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTaskLock", reflect.TypeOf((*MockModelInterface)(nil).RefreshTaskLock), ctx, arg)
}

// ReleaseTaskLockByWorker mocks base method.
func (m *MockModelInterface) ReleaseTaskLockByWorker(ctx context.Context, arg querier.ReleaseTaskLockByWorkerParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseTaskLockByWorker", ctx, arg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseTaskLockByWorker indicates an expected call of ReleaseTaskLockByWorker.
func (mr *MockModelInterfaceMockRecorder) ReleaseTaskLockByWorker(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseTaskLockByWorker", reflect.TypeOf((*MockModelInterface)(nil).ReleaseTaskLockByWorker), ctx, arg)
}

// RestoreUserByName mocks base method.
func (m *MockModelInterface) RestoreUserByName(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreUserByName", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreUserByName indicates an expected call of RestoreUserByName.
func (mr *MockModelInterfaceMockRecorder) RestoreUserByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreUserByName", reflect.TypeOf((*MockModelInterface)(nil).RestoreUserByName), ctx, name)
}

// RunTransaction mocks base method.
func (m *MockModelInterface) RunTransaction(ctx context.Context, f func(ModelInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransaction", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransaction indicates an expected call of RunTransaction.
func (mr *MockModelInterfaceMockRecorder) RunTransaction(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransaction", reflect.TypeOf((*MockModelInterface)(nil).RunTransaction), ctx, f)
}

// RunTransactionWithTx mocks base method.
func (m *MockModelInterface) RunTransactionWithTx(ctx context.Context, f func(core.Tx, ModelInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransactionWithTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransactionWithTx indicates an expected call of RunTransactionWithTx.
func (mr *MockModelInterfaceMockRecorder) RunTransactionWithTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransactionWithTx", reflect.TypeOf((*MockModelInterface)(nil).RunTransactionWithTx), ctx, f)
}

// SetUserDefaultOrg mocks base method.
func (m *MockModelInterface) SetUserDefaultOrg(ctx context.Context, arg querier.SetUserDefaultOrgParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserDefaultOrg", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserDefaultOrg indicates an expected call of SetUserDefaultOrg.
func (mr *MockModelInterfaceMockRecorder) SetUserDefaultOrg(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserDefaultOrg", reflect.TypeOf((*MockModelInterface)(nil).SetUserDefaultOrg), ctx, arg)
}

// SpawnWithTx mocks base method.
func (m *MockModelInterface) SpawnWithTx(tx core.Tx) ModelInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpawnWithTx", tx)
	ret0, _ := ret[0].(ModelInterface)
	return ret0
}

// SpawnWithTx indicates an expected call of SpawnWithTx.
func (mr *MockModelInterfaceMockRecorder) SpawnWithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnWithTx", reflect.TypeOf((*MockModelInterface)(nil).SpawnWithTx), tx)
}

// UpdatePendingTaskPriorityByLabels mocks base method.
func (m *MockModelInterface) UpdatePendingTaskPriorityByLabels(ctx context.Context, arg querier.UpdatePendingTaskPriorityByLabelsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePendingTaskPriorityByLabels", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePendingTaskPriorityByLabels indicates an expected call of UpdatePendingTaskPriorityByLabels.
func (mr *MockModelInterfaceMockRecorder) UpdatePendingTaskPriorityByLabels(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePendingTaskPriorityByLabels", reflect.TypeOf((*MockModelInterface)(nil).UpdatePendingTaskPriorityByLabels), ctx, arg)
}

// UpdatePendingTaskWeightByLabels mocks base method.
func (m *MockModelInterface) UpdatePendingTaskWeightByLabels(ctx context.Context, arg querier.UpdatePendingTaskWeightByLabelsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePendingTaskWeightByLabels", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePendingTaskWeightByLabels indicates an expected call of UpdatePendingTaskWeightByLabels.
func (mr *MockModelInterfaceMockRecorder) UpdatePendingTaskWeightByLabels(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePendingTaskWeightByLabels", reflect.TypeOf((*MockModelInterface)(nil).UpdatePendingTaskWeightByLabels), ctx, arg)
}

// UpdateTask mocks base method.
func (m *MockModelInterface) UpdateTask(ctx context.Context, arg querier.UpdateTaskParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockModelInterfaceMockRecorder) UpdateTask(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockModelInterface)(nil).UpdateTask), ctx, arg)
}

// UpdateTaskStartedAt mocks base method.
func (m *MockModelInterface) UpdateTaskStartedAt(ctx context.Context, arg querier.UpdateTaskStartedAtParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStartedAt", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStartedAt indicates an expected call of UpdateTaskStartedAt.
func (mr *MockModelInterfaceMockRecorder) UpdateTaskStartedAt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStartedAt", reflect.TypeOf((*MockModelInterface)(nil).UpdateTaskStartedAt), ctx, arg)
}

// UpdateTaskStartedAtByWorker mocks base method.
func (m *MockModelInterface) UpdateTaskStartedAtByWorker(ctx context.Context, arg querier.UpdateTaskStartedAtByWorkerParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStartedAtByWorker", ctx, arg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStartedAtByWorker indicates an expected call of UpdateTaskStartedAtByWorker.
func (mr *MockModelInterfaceMockRecorder) UpdateTaskStartedAtByWorker(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStartedAtByWorker", reflect.TypeOf((*MockModelInterface)(nil).UpdateTaskStartedAtByWorker), ctx, arg)
}

// UpdateTaskStatus mocks base method.
func (m *MockModelInterface) UpdateTaskStatus(ctx context.Context, arg querier.UpdateTaskStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockModelInterfaceMockRecorder) UpdateTaskStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockModelInterface)(nil).UpdateTaskStatus), ctx, arg)
}

// UpdateTaskStatusByWorker mocks base method.
func (m *MockModelInterface) UpdateTaskStatusByWorker(ctx context.Context, arg querier.UpdateTaskStatusByWorkerParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatusByWorker", ctx, arg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStatusByWorker indicates an expected call of UpdateTaskStatusByWorker.
func (mr *MockModelInterfaceMockRecorder) UpdateTaskStatusByWorker(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatusByWorker", reflect.TypeOf((*MockModelInterface)(nil).UpdateTaskStatusByWorker), ctx, arg)
}

// UpdateUserPassword mocks base method.
func (m *MockModelInterface) UpdateUserPassword(ctx context.Context, arg querier.UpdateUserPasswordParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockModelInterfaceMockRecorder) UpdateUserPassword(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockModelInterface)(nil).UpdateUserPassword), ctx, arg)
}

// UpdateWorkerAppliedConfigVersion mocks base method.
func (m *MockModelInterface) UpdateWorkerAppliedConfigVersion(ctx context.Context, arg querier.UpdateWorkerAppliedConfigVersionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkerAppliedConfigVersion", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkerAppliedConfigVersion indicates an expected call of UpdateWorkerAppliedConfigVersion.
func (mr *MockModelInterfaceMockRecorder) UpdateWorkerAppliedConfigVersion(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkerAppliedConfigVersion", reflect.TypeOf((*MockModelInterface)(nil).UpdateWorkerAppliedConfigVersion), ctx, arg)
}

// UpdateWorkerHeartbeat mocks base method.
func (m *MockModelInterface) UpdateWorkerHeartbeat(ctx context.Context, id uuid.UUID) (*querier.AnclaxWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkerHeartbeat", ctx, id)
	ret0, _ := ret[0].(*querier.AnclaxWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkerHeartbeat indicates an expected call of UpdateWorkerHeartbeat.
func (mr *MockModelInterfaceMockRecorder) UpdateWorkerHeartbeat(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkerHeartbeat", reflect.TypeOf((*MockModelInterface)(nil).UpdateWorkerHeartbeat), ctx, id)
}

// UpsertWorker mocks base method.
func (m *MockModelInterface) UpsertWorker(ctx context.Context, arg querier.UpsertWorkerParams) (*querier.AnclaxWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWorker", ctx, arg)
	ret0, _ := ret[0].(*querier.AnclaxWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWorker indicates an expected call of UpsertWorker.
func (mr *MockModelInterfaceMockRecorder) UpsertWorker(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWorker", reflect.TypeOf((*MockModelInterface)(nil).UpsertWorker), ctx, arg)
}

// VerifyTaskOwnership mocks base method.
func (m *MockModelInterface) VerifyTaskOwnership(ctx context.Context, arg querier.VerifyTaskOwnershipParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyTaskOwnership", ctx, arg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyTaskOwnership indicates an expected call of VerifyTaskOwnership.
func (mr *MockModelInterfaceMockRecorder) VerifyTaskOwnership(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyTaskOwnership", reflect.TypeOf((*MockModelInterface)(nil).VerifyTaskOwnership), ctx, arg)
}
