// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/taskcore/store/interfaces.go
//
// Generated by this command:
//
//	mockgen -source pkg/taskcore/store/interfaces.go -destination pkg/taskcore/store/mock_gen.go -package store
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	core "github.com/risingwavelabs/anclax/core"
	apigen "github.com/risingwavelabs/anclax/pkg/zgen/apigen"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskStoreInterface is a mock of TaskStoreInterface interface.
type MockTaskStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTaskStoreInterfaceMockRecorder
	isgomock struct{}
}

// MockTaskStoreInterfaceMockRecorder is the mock recorder for MockTaskStoreInterface.
type MockTaskStoreInterfaceMockRecorder struct {
	mock *MockTaskStoreInterface
}

// NewMockTaskStoreInterface creates a new mock instance.
func NewMockTaskStoreInterface(ctrl *gomock.Controller) *MockTaskStoreInterface {
	mock := &MockTaskStoreInterface{ctrl: ctrl}
	mock.recorder = &MockTaskStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskStoreInterface) EXPECT() *MockTaskStoreInterfaceMockRecorder {
	return m.recorder
}

// CancelTask mocks base method.
func (m *MockTaskStoreInterface) CancelTask(ctx context.Context, taskID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelTask indicates an expected call of CancelTask.
func (mr *MockTaskStoreInterfaceMockRecorder) CancelTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).CancelTask), ctx, taskID)
}

// CancelTaskWithTx mocks base method.
func (m *MockTaskStoreInterface) CancelTaskWithTx(ctx context.Context, tx core.Tx, taskID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTaskWithTx", ctx, tx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelTaskWithTx indicates an expected call of CancelTaskWithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) CancelTaskWithTx(ctx, tx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTaskWithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).CancelTaskWithTx), ctx, tx, taskID)
}

// GetLastTaskErrorEvent mocks base method.
func (m *MockTaskStoreInterface) GetLastTaskErrorEvent(ctx context.Context, taskID int32) (*apigen.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastTaskErrorEvent", ctx, taskID)
	ret0, _ := ret[0].(*apigen.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastTaskErrorEvent indicates an expected call of GetLastTaskErrorEvent.
func (mr *MockTaskStoreInterfaceMockRecorder) GetLastTaskErrorEvent(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastTaskErrorEvent", reflect.TypeOf((*MockTaskStoreInterface)(nil).GetLastTaskErrorEvent), ctx, taskID)
}

// GetLastTaskErrorEventWithTx mocks base method.
func (m *MockTaskStoreInterface) GetLastTaskErrorEventWithTx(ctx context.Context, tx core.Tx, taskID int32) (*apigen.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastTaskErrorEventWithTx", ctx, tx, taskID)
	ret0, _ := ret[0].(*apigen.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastTaskErrorEventWithTx indicates an expected call of GetLastTaskErrorEventWithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) GetLastTaskErrorEventWithTx(ctx, tx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastTaskErrorEventWithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).GetLastTaskErrorEventWithTx), ctx, tx, taskID)
}

// GetTaskByID mocks base method.
func (m *MockTaskStoreInterface) GetTaskByID(ctx context.Context, taskID int32) (*apigen.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, taskID)
	ret0, _ := ret[0].(*apigen.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockTaskStoreInterfaceMockRecorder) GetTaskByID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockTaskStoreInterface)(nil).GetTaskByID), ctx, taskID)
}

// GetTaskByIDWithTx mocks base method.
func (m *MockTaskStoreInterface) GetTaskByIDWithTx(ctx context.Context, tx core.Tx, taskID int32) (*apigen.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByIDWithTx", ctx, tx, taskID)
	ret0, _ := ret[0].(*apigen.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByIDWithTx indicates an expected call of GetTaskByIDWithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) GetTaskByIDWithTx(ctx, tx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByIDWithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).GetTaskByIDWithTx), ctx, tx, taskID)
}

// GetTaskByUniqueTag mocks base method.
func (m *MockTaskStoreInterface) GetTaskByUniqueTag(ctx context.Context, uniqueTag string) (*apigen.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByUniqueTag", ctx, uniqueTag)
	ret0, _ := ret[0].(*apigen.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByUniqueTag indicates an expected call of GetTaskByUniqueTag.
func (mr *MockTaskStoreInterfaceMockRecorder) GetTaskByUniqueTag(ctx, uniqueTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByUniqueTag", reflect.TypeOf((*MockTaskStoreInterface)(nil).GetTaskByUniqueTag), ctx, uniqueTag)
}

// GetTaskByUniqueTagWithTx mocks base method.
func (m *MockTaskStoreInterface) GetTaskByUniqueTagWithTx(ctx context.Context, tx core.Tx, uniqueTag string) (*apigen.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByUniqueTagWithTx", ctx, tx, uniqueTag)
	ret0, _ := ret[0].(*apigen.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByUniqueTagWithTx indicates an expected call of GetTaskByUniqueTagWithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) GetTaskByUniqueTagWithTx(ctx, tx, uniqueTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByUniqueTagWithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).GetTaskByUniqueTagWithTx), ctx, tx, uniqueTag)
}

// PauseTask mocks base method.
func (m *MockTaskStoreInterface) PauseTask(ctx context.Context, taskID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseTask indicates an expected call of PauseTask.
func (mr *MockTaskStoreInterfaceMockRecorder) PauseTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).PauseTask), ctx, taskID)
}

// PauseTaskWithTx mocks base method.
func (m *MockTaskStoreInterface) PauseTaskWithTx(ctx context.Context, tx core.Tx, taskID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseTaskWithTx", ctx, tx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseTaskWithTx indicates an expected call of PauseTaskWithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) PauseTaskWithTx(ctx, tx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseTaskWithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).PauseTaskWithTx), ctx, tx, taskID)
}

// PushTask mocks base method.
func (m *MockTaskStoreInterface) PushTask(ctx context.Context, task *apigen.Task) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushTask", ctx, task)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushTask indicates an expected call of PushTask.
func (mr *MockTaskStoreInterfaceMockRecorder) PushTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).PushTask), ctx, task)
}

// PushTaskWithTx mocks base method.
func (m *MockTaskStoreInterface) PushTaskWithTx(ctx context.Context, tx core.Tx, task *apigen.Task) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushTaskWithTx", ctx, tx, task)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushTaskWithTx indicates an expected call of PushTaskWithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) PushTaskWithTx(ctx, tx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushTaskWithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).PushTaskWithTx), ctx, tx, task)
}

// ResumeTask mocks base method.
func (m *MockTaskStoreInterface) ResumeTask(ctx context.Context, taskID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeTask indicates an expected call of ResumeTask.
func (mr *MockTaskStoreInterfaceMockRecorder) ResumeTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).ResumeTask), ctx, taskID)
}

// ResumeTaskWithTx mocks base method.
func (m *MockTaskStoreInterface) ResumeTaskWithTx(ctx context.Context, tx core.Tx, taskID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeTaskWithTx", ctx, tx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeTaskWithTx indicates an expected call of ResumeTaskWithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) ResumeTaskWithTx(ctx, tx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeTaskWithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).ResumeTaskWithTx), ctx, tx, taskID)
}

// UpdateCronJob mocks base method.
func (m *MockTaskStoreInterface) UpdateCronJob(ctx context.Context, taskID int32, cronExpression string, spec json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCronJob", ctx, taskID, cronExpression, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCronJob indicates an expected call of UpdateCronJob.
func (mr *MockTaskStoreInterfaceMockRecorder) UpdateCronJob(ctx, taskID, cronExpression, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCronJob", reflect.TypeOf((*MockTaskStoreInterface)(nil).UpdateCronJob), ctx, taskID, cronExpression, spec)
}

// UpdateCronJobWithTx mocks base method.
func (m *MockTaskStoreInterface) UpdateCronJobWithTx(ctx context.Context, tx core.Tx, taskID int32, cronExpression string, spec json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCronJobWithTx", ctx, tx, taskID, cronExpression, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCronJobWithTx indicates an expected call of UpdateCronJobWithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) UpdateCronJobWithTx(ctx, tx, taskID, cronExpression, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCronJobWithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).UpdateCronJobWithTx), ctx, tx, taskID, cronExpression, spec)
}

// UpdatePendingTaskPriorityByLabels mocks base method.
func (m *MockTaskStoreInterface) UpdatePendingTaskPriorityByLabels(ctx context.Context, labels []string, priority int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePendingTaskPriorityByLabels", ctx, labels, priority)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePendingTaskPriorityByLabels indicates an expected call of UpdatePendingTaskPriorityByLabels.
func (mr *MockTaskStoreInterfaceMockRecorder) UpdatePendingTaskPriorityByLabels(ctx, labels, priority any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePendingTaskPriorityByLabels", reflect.TypeOf((*MockTaskStoreInterface)(nil).UpdatePendingTaskPriorityByLabels), ctx, labels, priority)
}

// UpdatePendingTaskPriorityByLabelsWithTx mocks base method.
func (m *MockTaskStoreInterface) UpdatePendingTaskPriorityByLabelsWithTx(ctx context.Context, tx core.Tx, labels []string, priority int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePendingTaskPriorityByLabelsWithTx", ctx, tx, labels, priority)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePendingTaskPriorityByLabelsWithTx indicates an expected call of UpdatePendingTaskPriorityByLabelsWithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) UpdatePendingTaskPriorityByLabelsWithTx(ctx, tx, labels, priority any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePendingTaskPriorityByLabelsWithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).UpdatePendingTaskPriorityByLabelsWithTx), ctx, tx, labels, priority)
}

// UpdatePendingTaskWeightByLabels mocks base method.
func (m *MockTaskStoreInterface) UpdatePendingTaskWeightByLabels(ctx context.Context, labels []string, weight int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePendingTaskWeightByLabels", ctx, labels, weight)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePendingTaskWeightByLabels indicates an expected call of UpdatePendingTaskWeightByLabels.
func (mr *MockTaskStoreInterfaceMockRecorder) UpdatePendingTaskWeightByLabels(ctx, labels, weight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePendingTaskWeightByLabels", reflect.TypeOf((*MockTaskStoreInterface)(nil).UpdatePendingTaskWeightByLabels), ctx, labels, weight)
}

// UpdatePendingTaskWeightByLabelsWithTx mocks base method.
func (m *MockTaskStoreInterface) UpdatePendingTaskWeightByLabelsWithTx(ctx context.Context, tx core.Tx, labels []string, weight int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePendingTaskWeightByLabelsWithTx", ctx, tx, labels, weight)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePendingTaskWeightByLabelsWithTx indicates an expected call of UpdatePendingTaskWeightByLabelsWithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) UpdatePendingTaskWeightByLabelsWithTx(ctx, tx, labels, weight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePendingTaskWeightByLabelsWithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).UpdatePendingTaskWeightByLabelsWithTx), ctx, tx, labels, weight)
}

// WaitForTask mocks base method.
func (m *MockTaskStoreInterface) WaitForTask(ctx context.Context, taskID int32, opts ...WaitForTaskOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WaitForTask", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForTask indicates an expected call of WaitForTask.
func (mr *MockTaskStoreInterfaceMockRecorder) WaitForTask(ctx, taskID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).WaitForTask), varargs...)
}

// WaitForTaskWithTx mocks base method.
func (m *MockTaskStoreInterface) WaitForTaskWithTx(ctx context.Context, tx core.Tx, taskID int32, opts ...WaitForTaskOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tx, taskID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WaitForTaskWithTx", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForTaskWithTx indicates an expected call of WaitForTaskWithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) WaitForTaskWithTx(ctx, tx, taskID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tx, taskID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForTaskWithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).WaitForTaskWithTx), varargs...)
}
