// This file is generated by tools, DO NOT EDIT.
package taskgen

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/risingwavelabs/anclax/core"
	"github.com/risingwavelabs/anclax/pkg/zgen/apigen"
	taskcore "github.com/risingwavelabs/anclax/pkg/taskcore/store"
	"github.com/risingwavelabs/anclax/pkg/taskcore/worker"
	"github.com/risingwavelabs/anclax/pkg/utils"
	"github.com/pkg/errors"
)

func init() {
	utils.Noop()
}

const ( 
	DeleteOpaqueKey = "deleteOpaqueKey" 

	UpdateWorkerRuntimeConfig = "updateWorkerRuntimeConfig" 

	InterruptTask = "interruptTask" 

	StressProbe = "stressProbe" 
)



type TaskRunner interface { 
    // Delete an opaque key
	RunDeleteOpaqueKey(ctx context.Context, params *DeleteOpaqueKeyParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Delete an opaque key
	RunDeleteOpaqueKeyWithTx(ctx context.Context, tx core.Tx, params *DeleteOpaqueKeyParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Update worker runtime config and wait for alive workers to apply it
	RunUpdateWorkerRuntimeConfig(ctx context.Context, params *UpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Update worker runtime config and wait for alive workers to apply it
	RunUpdateWorkerRuntimeConfigWithTx(ctx context.Context, tx core.Tx, params *UpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Interrupt a task and stop any in-flight execution
	RunInterruptTask(ctx context.Context, params *InterruptTaskParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Interrupt a task and stop any in-flight execution
	RunInterruptTaskWithTx(ctx context.Context, tx core.Tx, params *InterruptTaskParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // No-op stress probe task for worker E2E benchmarking
	RunStressProbe(ctx context.Context, params *StressProbeParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // No-op stress probe task for worker E2E benchmarking
	RunStressProbeWithTx(ctx context.Context, tx core.Tx, params *StressProbeParameters, overrides ...taskcore.TaskOverride) (int32, error)
}

type Client struct {
	taskStore taskcore.TaskStoreInterface
	now       func() time.Time
}

func NewTaskRunner(taskStore taskcore.TaskStoreInterface) TaskRunner {
	return &Client{
		taskStore: taskStore,
		now:       time.Now,
	}
}


func (c *Client) RunDeleteOpaqueKey(ctx context.Context, params *DeleteOpaqueKeyParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runDeleteOpaqueKey(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunDeleteOpaqueKeyWithTx(ctx context.Context, tx core.Tx, params *DeleteOpaqueKeyParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runDeleteOpaqueKey(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runDeleteOpaqueKey(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *DeleteOpaqueKeyParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := params.Marshal()
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    DeleteOpaqueKey,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "30m",
		MaxAttempts: -1,
	}
	
	
	
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunUpdateWorkerRuntimeConfig(ctx context.Context, params *UpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runUpdateWorkerRuntimeConfig(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunUpdateWorkerRuntimeConfigWithTx(ctx context.Context, tx core.Tx, params *UpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runUpdateWorkerRuntimeConfig(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runUpdateWorkerRuntimeConfig(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *UpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := params.Marshal()
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    UpdateWorkerRuntimeConfig,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("20s")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "2s",
		MaxAttempts: -1,
	}
	
	
	attributes.Priority = utils.Ptr(int32(2147483647))
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunInterruptTask(ctx context.Context, params *InterruptTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runInterruptTask(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunInterruptTaskWithTx(ctx context.Context, tx core.Tx, params *InterruptTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runInterruptTask(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runInterruptTask(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *InterruptTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := params.Marshal()
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    InterruptTask,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("20s")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "2s",
		MaxAttempts: -1,
	}
	
	
	attributes.Priority = utils.Ptr(int32(2147483647))
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunStressProbe(ctx context.Context, params *StressProbeParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runStressProbe(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunStressProbeWithTx(ctx context.Context, tx core.Tx, params *StressProbeParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runStressProbe(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runStressProbe(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *StressProbeParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := params.Marshal()
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    StressProbe,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("30s")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "1s",
		MaxAttempts: 1,
	}
	
	
	
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}


type DeleteOpaqueKeyParameters struct { 
    // The ID of the opaque key to delete
	KeyID int64 `json:"keyID" yaml:"keyID"`
}



type UpdateWorkerRuntimeConfigParameters struct { 
    // Fallback retry interval when ack listening is unavailable
	NotifyInterval *string `json:"notifyInterval" yaml:"notifyInterval"`

    // Ack listen timeout window for one iteration
	ListenTimeout *string `json:"listenTimeout" yaml:"listenTimeout"`

    // Correlation ID for notify and ack messages
	RequestID *string `json:"requestID" yaml:"requestID"`

    // Maximum percentage of strict-priority slots (0-100)
	MaxStrictPercentage *int32 `json:"maxStrictPercentage" yaml:"maxStrictPercentage"`

    // Default weight for unlabeled task group
	DefaultWeight *int32 `json:"defaultWeight" yaml:"defaultWeight"`

    // Label names for weighted groups
	Labels []string `json:"labels" yaml:"labels"`

    // Weights for labels by index
	Weights []int32 `json:"weights" yaml:"weights"`
}


type InterruptTaskParameters struct { 
    // Correlation ID for notify and ack messages
	RequestID *string `json:"requestID" yaml:"requestID"`

    // Fallback retry interval when ack listening is unavailable
	NotifyInterval *string `json:"notifyInterval" yaml:"notifyInterval"`

    // Ack listen timeout window for one iteration
	ListenTimeout *string `json:"listenTimeout" yaml:"listenTimeout"`

    // Task IDs to interrupt
	TaskIDs []int32 `json:"taskIDs" yaml:"taskIDs"`
}

type StressProbeParameters struct { 
    // Logical group name for test-side metrics and labels
	Group string `json:"group" yaml:"group"`

    // Logical task id for stress-run metrics correlation
	JobID int64 `json:"jobID" yaml:"jobID"`

    // Simulated task execution time in milliseconds
	SleepMs int32 `json:"sleepMs" yaml:"sleepMs"`
}

func (r *DeleteOpaqueKeyParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *DeleteOpaqueKeyParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}
func (r *UpdateWorkerRuntimeConfigParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *UpdateWorkerRuntimeConfigParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}
func (r *InterruptTaskParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *InterruptTaskParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}
func (r *StressProbeParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *StressProbeParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

type ExecutorInterface interface { 
     // Delete an opaque key
	ExecuteDeleteOpaqueKey(ctx context.Context, params *DeleteOpaqueKeyParameters) error
 
	// Hook called when deleteOpaqueKey fails
	OnDeleteOpaqueKeyFailed(ctx context.Context, taskID int32, params *DeleteOpaqueKeyParameters, tx core.Tx) error

     // Update worker runtime config and wait for alive workers to apply it
	ExecuteUpdateWorkerRuntimeConfig(ctx context.Context, params *UpdateWorkerRuntimeConfigParameters) error
 

     // Interrupt a task and stop any in-flight execution
	ExecuteInterruptTask(ctx context.Context, params *InterruptTaskParameters) error
 

     // No-op stress probe task for worker E2E benchmarking
	ExecuteStressProbe(ctx context.Context, params *StressProbeParameters) error
 
}

type TaskHandler struct {
	executor ExecutorInterface

	externalTaskHandler []worker.TaskHandler
}

func NewTaskHandler(executor ExecutorInterface) worker.TaskHandler {
	return &TaskHandler{
		executor: executor,
	}
}

func (f *TaskHandler) RegisterTaskHandler(handler worker.TaskHandler) {
	f.externalTaskHandler = append(f.externalTaskHandler, handler)
}

func (f *TaskHandler) HandleTask(ctx context.Context, spec worker.TaskSpec) error {
	for _, handler := range f.externalTaskHandler {
		if err := handler.HandleTask(ctx, spec); err != nil {
			if errors.Is(err, worker.ErrUnknownTaskType) {
				continue
			}
			return err
		}
		return nil
	}

	switch spec.GetType() { 
	case DeleteOpaqueKey:
		var params DeleteOpaqueKeyParameters
		if err := params.Parse(spec.GetPayload()); err != nil {
			return fmt.Errorf("failed to parse deleteOpaqueKey parameters: %w", err)
		}
		return f.executor.ExecuteDeleteOpaqueKey(ctx, &params)
		
	case UpdateWorkerRuntimeConfig:
		var params UpdateWorkerRuntimeConfigParameters
		if err := params.Parse(spec.GetPayload()); err != nil {
			return fmt.Errorf("failed to parse updateWorkerRuntimeConfig parameters: %w", err)
		}
		return f.executor.ExecuteUpdateWorkerRuntimeConfig(ctx, &params)
		
	case InterruptTask:
		var params InterruptTaskParameters
		if err := params.Parse(spec.GetPayload()); err != nil {
			return fmt.Errorf("failed to parse interruptTask parameters: %w", err)
		}
		return f.executor.ExecuteInterruptTask(ctx, &params)
		
	case StressProbe:
		var params StressProbeParameters
		if err := params.Parse(spec.GetPayload()); err != nil {
			return fmt.Errorf("failed to parse stressProbe parameters: %w", err)
		}
		return f.executor.ExecuteStressProbe(ctx, &params)
		
	default:
		return errors.Wrapf(worker.ErrUnknownTaskType, "unknown task type: %s", spec.GetType())
	}
}

func (f *TaskHandler) OnTaskFailed(ctx context.Context, tx core.Tx, failedTaskSpec worker.TaskSpec, taskID int32) error {
	for _, handler := range f.externalTaskHandler {
		if err := handler.OnTaskFailed(ctx, tx, failedTaskSpec, taskID); err != nil {
			if errors.Is(err, worker.ErrUnknownTaskType) {
				continue
			}
			return err
		}
		return nil
	}

	// Call the appropriate OnXXXFailed hook method
	switch failedTaskSpec.GetType() { 
	case DeleteOpaqueKey:
		var params DeleteOpaqueKeyParameters
		if err := params.Parse(failedTaskSpec.GetPayload()); err != nil {
			return fmt.Errorf("failed to parse deleteOpaqueKey parameters: %w", err)
		}
		return f.executor.OnDeleteOpaqueKeyFailed(ctx, taskID, &params, tx)
	default:
		return nil // No hook configured for this task type
	}
}
