// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/zgen/taskgen/runner_gen.go
//
// Generated by this command:
//
//	mockgen -source pkg/zgen/taskgen/runner_gen.go -destination pkg/zgen/taskgen/runner_gen_mock.go -package taskgen
//

// Package taskgen is a generated GoMock package.
package taskgen

import (
	context "context"
	reflect "reflect"

	core "github.com/risingwavelabs/anclax/core"
	store "github.com/risingwavelabs/anclax/pkg/taskcore/store"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRunner is a mock of TaskRunner interface.
type MockTaskRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRunnerMockRecorder
	isgomock struct{}
}

// MockTaskRunnerMockRecorder is the mock recorder for MockTaskRunner.
type MockTaskRunnerMockRecorder struct {
	mock *MockTaskRunner
}

// NewMockTaskRunner creates a new mock instance.
func NewMockTaskRunner(ctrl *gomock.Controller) *MockTaskRunner {
	mock := &MockTaskRunner{ctrl: ctrl}
	mock.recorder = &MockTaskRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRunner) EXPECT() *MockTaskRunnerMockRecorder {
	return m.recorder
}

// RunDeleteOpaqueKey mocks base method.
func (m *MockTaskRunner) RunDeleteOpaqueKey(ctx context.Context, params *DeleteOpaqueKeyParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunDeleteOpaqueKey", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunDeleteOpaqueKey indicates an expected call of RunDeleteOpaqueKey.
func (mr *MockTaskRunnerMockRecorder) RunDeleteOpaqueKey(ctx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunDeleteOpaqueKey", reflect.TypeOf((*MockTaskRunner)(nil).RunDeleteOpaqueKey), varargs...)
}

// RunDeleteOpaqueKeyWithTx mocks base method.
func (m *MockTaskRunner) RunDeleteOpaqueKeyWithTx(ctx context.Context, tx core.Tx, params *DeleteOpaqueKeyParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunDeleteOpaqueKeyWithTx", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunDeleteOpaqueKeyWithTx indicates an expected call of RunDeleteOpaqueKeyWithTx.
func (mr *MockTaskRunnerMockRecorder) RunDeleteOpaqueKeyWithTx(ctx, tx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunDeleteOpaqueKeyWithTx", reflect.TypeOf((*MockTaskRunner)(nil).RunDeleteOpaqueKeyWithTx), varargs...)
}

// RunInterruptTask mocks base method.
func (m *MockTaskRunner) RunInterruptTask(ctx context.Context, params *InterruptTaskParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunInterruptTask", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunInterruptTask indicates an expected call of RunInterruptTask.
func (mr *MockTaskRunnerMockRecorder) RunInterruptTask(ctx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInterruptTask", reflect.TypeOf((*MockTaskRunner)(nil).RunInterruptTask), varargs...)
}

// RunInterruptTaskWithTx mocks base method.
func (m *MockTaskRunner) RunInterruptTaskWithTx(ctx context.Context, tx core.Tx, params *InterruptTaskParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunInterruptTaskWithTx", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunInterruptTaskWithTx indicates an expected call of RunInterruptTaskWithTx.
func (mr *MockTaskRunnerMockRecorder) RunInterruptTaskWithTx(ctx, tx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInterruptTaskWithTx", reflect.TypeOf((*MockTaskRunner)(nil).RunInterruptTaskWithTx), varargs...)
}

// RunStressProbe mocks base method.
func (m *MockTaskRunner) RunStressProbe(ctx context.Context, params *StressProbeParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunStressProbe", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunStressProbe indicates an expected call of RunStressProbe.
func (mr *MockTaskRunnerMockRecorder) RunStressProbe(ctx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunStressProbe", reflect.TypeOf((*MockTaskRunner)(nil).RunStressProbe), varargs...)
}

// RunStressProbeWithTx mocks base method.
func (m *MockTaskRunner) RunStressProbeWithTx(ctx context.Context, tx core.Tx, params *StressProbeParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunStressProbeWithTx", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunStressProbeWithTx indicates an expected call of RunStressProbeWithTx.
func (mr *MockTaskRunnerMockRecorder) RunStressProbeWithTx(ctx, tx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunStressProbeWithTx", reflect.TypeOf((*MockTaskRunner)(nil).RunStressProbeWithTx), varargs...)
}

// RunUpdateWorkerRuntimeConfig mocks base method.
func (m *MockTaskRunner) RunUpdateWorkerRuntimeConfig(ctx context.Context, params *UpdateWorkerRuntimeConfigParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunUpdateWorkerRuntimeConfig", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunUpdateWorkerRuntimeConfig indicates an expected call of RunUpdateWorkerRuntimeConfig.
func (mr *MockTaskRunnerMockRecorder) RunUpdateWorkerRuntimeConfig(ctx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunUpdateWorkerRuntimeConfig", reflect.TypeOf((*MockTaskRunner)(nil).RunUpdateWorkerRuntimeConfig), varargs...)
}

// RunUpdateWorkerRuntimeConfigWithTx mocks base method.
func (m *MockTaskRunner) RunUpdateWorkerRuntimeConfigWithTx(ctx context.Context, tx core.Tx, params *UpdateWorkerRuntimeConfigParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunUpdateWorkerRuntimeConfigWithTx", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunUpdateWorkerRuntimeConfigWithTx indicates an expected call of RunUpdateWorkerRuntimeConfigWithTx.
func (mr *MockTaskRunnerMockRecorder) RunUpdateWorkerRuntimeConfigWithTx(ctx, tx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunUpdateWorkerRuntimeConfigWithTx", reflect.TypeOf((*MockTaskRunner)(nil).RunUpdateWorkerRuntimeConfigWithTx), varargs...)
}

// MockExecutorInterface is a mock of ExecutorInterface interface.
type MockExecutorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorInterfaceMockRecorder
	isgomock struct{}
}

// MockExecutorInterfaceMockRecorder is the mock recorder for MockExecutorInterface.
type MockExecutorInterfaceMockRecorder struct {
	mock *MockExecutorInterface
}

// NewMockExecutorInterface creates a new mock instance.
func NewMockExecutorInterface(ctrl *gomock.Controller) *MockExecutorInterface {
	mock := &MockExecutorInterface{ctrl: ctrl}
	mock.recorder = &MockExecutorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutorInterface) EXPECT() *MockExecutorInterfaceMockRecorder {
	return m.recorder
}

// ExecuteDeleteOpaqueKey mocks base method.
func (m *MockExecutorInterface) ExecuteDeleteOpaqueKey(ctx context.Context, params *DeleteOpaqueKeyParameters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteDeleteOpaqueKey", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteDeleteOpaqueKey indicates an expected call of ExecuteDeleteOpaqueKey.
func (mr *MockExecutorInterfaceMockRecorder) ExecuteDeleteOpaqueKey(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDeleteOpaqueKey", reflect.TypeOf((*MockExecutorInterface)(nil).ExecuteDeleteOpaqueKey), ctx, params)
}

// ExecuteInterruptTask mocks base method.
func (m *MockExecutorInterface) ExecuteInterruptTask(ctx context.Context, params *InterruptTaskParameters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteInterruptTask", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteInterruptTask indicates an expected call of ExecuteInterruptTask.
func (mr *MockExecutorInterfaceMockRecorder) ExecuteInterruptTask(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteInterruptTask", reflect.TypeOf((*MockExecutorInterface)(nil).ExecuteInterruptTask), ctx, params)
}

// ExecuteStressProbe mocks base method.
func (m *MockExecutorInterface) ExecuteStressProbe(ctx context.Context, params *StressProbeParameters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteStressProbe", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteStressProbe indicates an expected call of ExecuteStressProbe.
func (mr *MockExecutorInterfaceMockRecorder) ExecuteStressProbe(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteStressProbe", reflect.TypeOf((*MockExecutorInterface)(nil).ExecuteStressProbe), ctx, params)
}

// ExecuteUpdateWorkerRuntimeConfig mocks base method.
func (m *MockExecutorInterface) ExecuteUpdateWorkerRuntimeConfig(ctx context.Context, params *UpdateWorkerRuntimeConfigParameters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteUpdateWorkerRuntimeConfig", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteUpdateWorkerRuntimeConfig indicates an expected call of ExecuteUpdateWorkerRuntimeConfig.
func (mr *MockExecutorInterfaceMockRecorder) ExecuteUpdateWorkerRuntimeConfig(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteUpdateWorkerRuntimeConfig", reflect.TypeOf((*MockExecutorInterface)(nil).ExecuteUpdateWorkerRuntimeConfig), ctx, params)
}

// OnDeleteOpaqueKeyFailed mocks base method.
func (m *MockExecutorInterface) OnDeleteOpaqueKeyFailed(ctx context.Context, taskID int32, params *DeleteOpaqueKeyParameters, tx core.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnDeleteOpaqueKeyFailed", ctx, taskID, params, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnDeleteOpaqueKeyFailed indicates an expected call of OnDeleteOpaqueKeyFailed.
func (mr *MockExecutorInterfaceMockRecorder) OnDeleteOpaqueKeyFailed(ctx, taskID, params, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDeleteOpaqueKeyFailed", reflect.TypeOf((*MockExecutorInterface)(nil).OnDeleteOpaqueKeyFailed), ctx, taskID, params, tx)
}
