// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/zgen/taskgen/taskgen_gen.go
//
// Generated by this command:
//
//	mockgen -source pkg/zgen/taskgen/taskgen_gen.go -destination pkg/zgen/taskgen/mock_gen.go -package taskgen
//

// Package taskgen is a generated GoMock package.
package taskgen

import (
	context "context"
	reflect "reflect"

	core "github.com/risingwavelabs/anclax/core"
	store "github.com/risingwavelabs/anclax/pkg/taskcore/store"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRunner is a mock of TaskRunner interface.
type MockTaskRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRunnerMockRecorder
	isgomock struct{}
}

// MockTaskRunnerMockRecorder is the mock recorder for MockTaskRunner.
type MockTaskRunnerMockRecorder struct {
	mock *MockTaskRunner
}

// NewMockTaskRunner creates a new mock instance.
func NewMockTaskRunner(ctrl *gomock.Controller) *MockTaskRunner {
	mock := &MockTaskRunner{ctrl: ctrl}
	mock.recorder = &MockTaskRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRunner) EXPECT() *MockTaskRunnerMockRecorder {
	return m.recorder
}

// RunAutoIncrementCounter mocks base method.
func (m *MockTaskRunner) RunAutoIncrementCounter(ctx context.Context, params *AutoIncrementCounterParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunAutoIncrementCounter", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunAutoIncrementCounter indicates an expected call of RunAutoIncrementCounter.
func (mr *MockTaskRunnerMockRecorder) RunAutoIncrementCounter(ctx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAutoIncrementCounter", reflect.TypeOf((*MockTaskRunner)(nil).RunAutoIncrementCounter), varargs...)
}

// RunAutoIncrementCounterWithTx mocks base method.
func (m *MockTaskRunner) RunAutoIncrementCounterWithTx(ctx context.Context, tx core.Tx, params *AutoIncrementCounterParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunAutoIncrementCounterWithTx", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunAutoIncrementCounterWithTx indicates an expected call of RunAutoIncrementCounterWithTx.
func (mr *MockTaskRunnerMockRecorder) RunAutoIncrementCounterWithTx(ctx, tx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAutoIncrementCounterWithTx", reflect.TypeOf((*MockTaskRunner)(nil).RunAutoIncrementCounterWithTx), varargs...)
}

// RunIncrementCounter mocks base method.
func (m *MockTaskRunner) RunIncrementCounter(ctx context.Context, params *IncrementCounterParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunIncrementCounter", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunIncrementCounter indicates an expected call of RunIncrementCounter.
func (mr *MockTaskRunnerMockRecorder) RunIncrementCounter(ctx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunIncrementCounter", reflect.TypeOf((*MockTaskRunner)(nil).RunIncrementCounter), varargs...)
}

// RunIncrementCounterWithTx mocks base method.
func (m *MockTaskRunner) RunIncrementCounterWithTx(ctx context.Context, tx core.Tx, params *IncrementCounterParameters, overrides ...store.TaskOverride) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tx, params}
	for _, a := range overrides {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunIncrementCounterWithTx", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunIncrementCounterWithTx indicates an expected call of RunIncrementCounterWithTx.
func (mr *MockTaskRunnerMockRecorder) RunIncrementCounterWithTx(ctx, tx, params any, overrides ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tx, params}, overrides...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunIncrementCounterWithTx", reflect.TypeOf((*MockTaskRunner)(nil).RunIncrementCounterWithTx), varargs...)
}

// MockExecutorInterface is a mock of ExecutorInterface interface.
type MockExecutorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorInterfaceMockRecorder
	isgomock struct{}
}

// MockExecutorInterfaceMockRecorder is the mock recorder for MockExecutorInterface.
type MockExecutorInterfaceMockRecorder struct {
	mock *MockExecutorInterface
}

// NewMockExecutorInterface creates a new mock instance.
func NewMockExecutorInterface(ctrl *gomock.Controller) *MockExecutorInterface {
	mock := &MockExecutorInterface{ctrl: ctrl}
	mock.recorder = &MockExecutorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutorInterface) EXPECT() *MockExecutorInterfaceMockRecorder {
	return m.recorder
}

// ExecuteAutoIncrementCounter mocks base method.
func (m *MockExecutorInterface) ExecuteAutoIncrementCounter(ctx context.Context, params *AutoIncrementCounterParameters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteAutoIncrementCounter", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteAutoIncrementCounter indicates an expected call of ExecuteAutoIncrementCounter.
func (mr *MockExecutorInterfaceMockRecorder) ExecuteAutoIncrementCounter(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteAutoIncrementCounter", reflect.TypeOf((*MockExecutorInterface)(nil).ExecuteAutoIncrementCounter), ctx, params)
}

// ExecuteIncrementCounter mocks base method.
func (m *MockExecutorInterface) ExecuteIncrementCounter(ctx context.Context, params *IncrementCounterParameters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteIncrementCounter", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteIncrementCounter indicates an expected call of ExecuteIncrementCounter.
func (mr *MockExecutorInterfaceMockRecorder) ExecuteIncrementCounter(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteIncrementCounter", reflect.TypeOf((*MockExecutorInterface)(nil).ExecuteIncrementCounter), ctx, params)
}
