// This file is generated by tools, DO NOT EDIT.
package taskgen

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/risingwavelabs/anclax/core"
	"github.com/risingwavelabs/anclax/pkg/zgen/apigen"
	taskcore "github.com/risingwavelabs/anclax/pkg/taskcore/store"
	"github.com/risingwavelabs/anclax/pkg/taskcore/worker"
	"github.com/risingwavelabs/anclax/pkg/utils"
	"github.com/pkg/errors"
)

func init() {
	utils.Noop()
}

const ( 
	AutoIncrementCounter = "AutoIncrementCounter" 

	IncrementCounter = "IncrementCounter" 
)



type TaskRunner interface { 
    // Increment the counter
	RunAutoIncrementCounter(ctx context.Context, params *AutoIncrementCounterParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Increment the counter
	RunAutoIncrementCounterWithTx(ctx context.Context, tx core.Tx, params *AutoIncrementCounterParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Increment the counter
	RunIncrementCounter(ctx context.Context, params *IncrementCounterParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Increment the counter
	RunIncrementCounterWithTx(ctx context.Context, tx core.Tx, params *IncrementCounterParameters, overrides ...taskcore.TaskOverride) (int32, error)
}

type Client struct {
	taskStore taskcore.TaskStoreInterface
	now       func() time.Time
}

func NewTaskRunner(taskStore taskcore.TaskStoreInterface) TaskRunner {
	return &Client{
		taskStore: taskStore,
		now:       time.Now,
	}
}


func (c *Client) RunAutoIncrementCounter(ctx context.Context, params *AutoIncrementCounterParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runAutoIncrementCounter(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunAutoIncrementCounterWithTx(ctx context.Context, tx core.Tx, params *AutoIncrementCounterParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runAutoIncrementCounter(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runAutoIncrementCounter(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *AutoIncrementCounterParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := params.Marshal()
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    AutoIncrementCounter,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "30m",
		MaxAttempts: -1,
	}
	attributes.Cronjob = &apigen.TaskCronjob{
		CronExpression: "*/5 * * * * *",
	}
	
	
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunIncrementCounter(ctx context.Context, params *IncrementCounterParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runIncrementCounter(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunIncrementCounterWithTx(ctx context.Context, tx core.Tx, params *IncrementCounterParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runIncrementCounter(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runIncrementCounter(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *IncrementCounterParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := params.Marshal()
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    IncrementCounter,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "30m",
		MaxAttempts: -1,
	}
	
	
	
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}


type AutoIncrementCounterParameters struct { 
    // 
	Amount int32 `json:"amount" yaml:"amount"`
}

type IncrementCounterParameters struct { 
    // 
	Amount int32 `json:"amount" yaml:"amount"`
}

func (r *AutoIncrementCounterParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *AutoIncrementCounterParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}
func (r *IncrementCounterParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *IncrementCounterParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

type ExecutorInterface interface { 
     // Increment the counter
	ExecuteAutoIncrementCounter(ctx context.Context, params *AutoIncrementCounterParameters) error
 

     // Increment the counter
	ExecuteIncrementCounter(ctx context.Context, params *IncrementCounterParameters) error
 
}

type TaskHandler struct {
	executor ExecutorInterface

	externalTaskHandler []worker.TaskHandler
}

func NewTaskHandler(executor ExecutorInterface) worker.TaskHandler {
	return &TaskHandler{
		executor: executor,
	}
}

func (f *TaskHandler) RegisterTaskHandler(handler worker.TaskHandler) {
	f.externalTaskHandler = append(f.externalTaskHandler, handler)
}

func (f *TaskHandler) HandleTask(ctx context.Context, spec worker.TaskSpec) error {
	for _, handler := range f.externalTaskHandler {
		if err := handler.HandleTask(ctx, spec); err != nil {
			if errors.Is(err, worker.ErrUnknownTaskType) {
				continue
			}
			return err
		}
		return nil
	}

	switch spec.GetType() { 
	case AutoIncrementCounter:
		var params AutoIncrementCounterParameters
		if err := params.Parse(spec.GetPayload()); err != nil {
			return fmt.Errorf("failed to parse AutoIncrementCounter parameters: %w", err)
		}
		return f.executor.ExecuteAutoIncrementCounter(ctx, &params)
		
	case IncrementCounter:
		var params IncrementCounterParameters
		if err := params.Parse(spec.GetPayload()); err != nil {
			return fmt.Errorf("failed to parse IncrementCounter parameters: %w", err)
		}
		return f.executor.ExecuteIncrementCounter(ctx, &params)
		
	default:
		return errors.Wrapf(worker.ErrUnknownTaskType, "unknown task type: %s", spec.GetType())
	}
}

func (f *TaskHandler) OnTaskFailed(ctx context.Context, tx core.Tx, failedTaskSpec worker.TaskSpec, taskID int32) error {
	for _, handler := range f.externalTaskHandler {
		if err := handler.OnTaskFailed(ctx, tx, failedTaskSpec, taskID); err != nil {
			if errors.Is(err, worker.ErrUnknownTaskType) {
				continue
			}
			return err
		}
		return nil
	}

	// Call the appropriate OnXXXFailed hook method
	switch failedTaskSpec.GetType() { 
	default:
		return nil // No hook configured for this task type
	}
}
