// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/risingwavelabs/anclax/pkg/app"
	"github.com/risingwavelabs/anclax/pkg/app/closer"
	"github.com/risingwavelabs/anclax/pkg/asynctask"
	"github.com/risingwavelabs/anclax/pkg/auth"
	"github.com/risingwavelabs/anclax/pkg/config"
	"github.com/risingwavelabs/anclax/pkg/controller"
	"github.com/risingwavelabs/anclax/pkg/globalctx"
	"github.com/risingwavelabs/anclax/pkg/hooks"
	"github.com/risingwavelabs/anclax/pkg/macaroons"
	store2 "github.com/risingwavelabs/anclax/pkg/macaroons/store"
	"github.com/risingwavelabs/anclax/pkg/metrics"
	"github.com/risingwavelabs/anclax/pkg/server"
	"github.com/risingwavelabs/anclax/pkg/service"
	"github.com/risingwavelabs/anclax/pkg/taskcore/ctrl"
	"github.com/risingwavelabs/anclax/pkg/taskcore/store"
	"github.com/risingwavelabs/anclax/pkg/zcore/model"
	"github.com/risingwavelabs/anclax/pkg/zgen/taskgen"
)

// Injectors from wire.go:

func InitializeApplication(cfg *config.Config, libCfg *config.LibConfig) (*app.Application, error) {
	globalContext := globalctx.New()
	closerManager := closer.NewCloserManager()
	modelInterface, err := model.NewModel(cfg, libCfg, closerManager)
	if err != nil {
		return nil, err
	}
	taskStoreInterface := store.NewTaskStore(modelInterface)
	taskRunner := taskgen.NewTaskRunner(taskStoreInterface)
	keyStore := store2.NewStore(modelInterface, taskRunner)
	caveatParserInterface := macaroons.NewCaveatParser()
	macaroonManagerInterface := macaroons.NewMacaroonManager(keyStore, caveatParserInterface)
	anclaxHookInterface := hooks.NewBaseHook()
	authInterface, err := auth.NewAuth(cfg, macaroonManagerInterface, caveatParserInterface, anclaxHookInterface)
	if err != nil {
		return nil, err
	}
	serviceInterface := service.NewService(cfg, modelInterface, authInterface, anclaxHookInterface)
	serverInterface := controller.NewController(serviceInterface, authInterface, cfg)
	validator := controller.NewValidator(modelInterface, authInterface)
	serverServer, err := server.NewServer(cfg, libCfg, globalContext, authInterface, serverInterface, validator)
	if err != nil {
		return nil, err
	}
	metricsServer := metrics.NewMetricsServer(cfg, globalContext)
	executorInterface := asynctask.NewExecutor(cfg, modelInterface)
	taskHandler := taskgen.NewTaskHandler(executorInterface)
	workerInterface, err := NewConfiguredWorker(globalContext, cfg, modelInterface, taskHandler)
	if err != nil {
		return nil, err
	}
	debugServer := app.NewDebugServer(cfg, globalContext)
	workerControlPlane := ctrl.NewWorkerControlPlane(modelInterface, taskRunner, taskStoreInterface)
	application, err := app.NewApplication(globalContext, cfg, serverServer, metricsServer, workerInterface, debugServer, authInterface, taskStoreInterface, workerControlPlane, serviceInterface, anclaxHookInterface, caveatParserInterface, closerManager)
	if err != nil {
		return nil, err
	}
	return application, nil
}
